services:
  whisper_cpp:
    image: whisper_cpp
    build:
      context: .
    ports:
      - '50022:50022'
  voicevox:
    image: voicevox/voicevox_engine:cpu-latest
    ports:
      - '50021:50021'
    restart: unless-stopped
